data(iris)
head(iris)
summary(iris)
dim(iris)
names(iris)
str(iris)
png("histogram.png");hist(iris$Sepal.Length,col='steelblue',main='Histogram',xlab='Length',ylab='Frequency');dev.off()
plot(iris$Sepal.Width,iris$Sepal.Length,main='Scatterplot',xlab='Sepal Width',ylab='Sepal Length',pch=19)
boxplot(Sepal.Length~Species,data=iris,main='Sepal Length by Species',xlab='Species',ylab='Sepal Length',col='steelblue',border='black')
